@startuml system-tests-c4
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title System Tests

Person(developer, "Developer")

System_Boundary(github, "GitHub") {
    Container(github_ui, "GitHub UI")
    Container(github_system, "GitHub System")
    Container(controller_workflow, "Controller Workflow")
    Container(reusable_test, "Reusable Test Workflow")
    Container(reusable_semver, "Reusable Semver Workflow")
    Container(reusable_build_push, "Reusable Build & Push Workflow")
}

System_Boundary(ghcr, "GitHub Container Registry", "GHCR") {
    Container(sample_service_image, "Sample Service Image")
}

System_Boundary(codecov, "CodeCov Service") {
    Container(coverage_report, "Coverage Report")
}

Rel(developer, github_ui, "creates pull request")
Rel(github_ui, github_system, "invoke pr create process")

Rel(github_system, controller_workflow, "runs on", "opened")

Rel(controller_workflow, reusable_test, "uses")
Rel(controller_workflow, reusable_semver, "uses")
Rel(controller_workflow, reusable_build_push, "uses")

Rel(reusable_build_push, sample_service_image, "creates, pushes")

Rel(reusable_test, coverage_report, "creates")f

@enduml