language: python
python: "3.7"
sudo: required

services:
  - docker

env:

before_install:
  - docker version

install:
  - pip install pipenv coverage pytest-cov python-coveralls flake8
  - pipenv install --dev
  - docker pull kbase/kb-sdk
  - cd ..
  - docker run kbase/kb-sdk genscript > kb-sdk
  - export KBSDK=$(pwd)/kb-sdk
  - chmod a+x $KBSDK
  - cd -
  - $KBSDK version

script:
  - $KBSDK validate
  - make test-sdkless
  # TODO make tests for the full stack with local auth, ws

after_success:
  - coveralls
