name: Lint with Black

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./lib"
          version: "22.1.0"
          exclude: '.+Impl.py'
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./test"
          version: "22.1.0"
