---
name: Manual
on:
 workflow_dispatch:
jobs:
  test:
    uses: ./.github/workflows/reusable_test-python.yml
  build-push:
    needs: test
    uses: ./.github/workflows/reusable_build-push.yml
    secrets: inherit
    with:
      name: '${{ github.event.repository.name }}'
      tags: 'br-${{ github.ref_name }}'
