---
name: PR to develop opened
on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - reopened
      - synchronize
jobs:
    test:
      uses: ./.github/workflows/reusable_test-python.yml
  build-push:
    needs: test
    uses: ./.github/workflows/reusable_build-push.yml
    with:
      name: '${{ github.event.repository.name }}-develop'
      push: false
      tag: ignore
    secrets: inherit
