---
name: Test, Build Image, Push Image for Pull Requests
on:
  pull_request:
    branches:
      - master
      - develop
jobs:
  #  test:
  #    uses: ./.github/workflows/test.yml
  build_push:
    #    needs: test
    uses: ./.github/workflows/build-push-image.yml
    with:
      tag: 'pr-${{github.event.pull_request.number}}'
    secrets:
      ghcr_username: ${{ secrets.GHCR_USERNAME }}
      ghcr_token: ${{ secrets.GHCR_TOKEN }}

