---
name: Test a Pull Request
on:
  pull_request:
    branches:
      - master
      - develop
    types:
      - opened
      - edited
      - reopened
      - synchronize
jobs:
  test:
    uses: ./.github/workflows/test.yml
