---
name: PR - Test
on:
  pull_request:
    branches:
      - master
      - develop
    types:
      - opened
      - reopened
      - synchronize
jobs:
  test:
    uses: ./.github/workflows/reusable-test.yml
