---
name: Release - Test, Build & Push Image
on:
  release:
    branches:
      - master
    types: [ published ]
jobs:
  ensure-semver:
    uses: ./.github/workflows/reusable_validate-release-tag.yml
    with:
      release_tag: '${{ github.event.release.tag_name }}'
  test:
    needs: ensure-semver
    uses: ./.github/workflows/reusable_test-python.yml
  build-push:
    needs: test
    uses: ./.github/workflows/reusable_build-push.yml
    with:
      name: '${{ github.event.repository.name }}'
      tags: '${{ github.event.release.tag_name }},latest'
    secrets: inherit
