---
name: Release - Test, Build & Push Image
on:
  release:
    branches:
      - master
    types: [ published ]
jobs:
  ensure-semver:
    uses: ./.github/workflows/reusable_ensure-semver.yml
  test:
    uses: ./.github/workflows/reusable_test-python.yml
  build-push:
    needs: test
    uses: ./.github/workflows/reusable_build-push.yml
    with:
      name: ${{ github.event.repository.name }}
      tag: latest
    secrets: inherit
