---
name: Release - Test, Build & Push Image
on:
  release:
    branches:
      - master
    types: [ published ]
jobs:
  test:
    uses: ./.github/workflows/reusable-test.yml
  build-push:
    needs: test
    uses: ./.github/workflows/reusable-build-push.yml
    with:
      name: ${{ github.repository }}
      tag: ${{ github.event.release.tag_name }}
    secrets: inherit
