---
name: Release - Test, Build & Push Image
on:
  release:
    branches:
      - master
    types: [ published ]
jobs:
  test:
    uses: ./.github/workflows/test.yml
  build-push:
    needs: test
    uses: ./.github/workflows/build-push.yml
    with:
      tag: ${{ github.event.release.tag_name }}
    secrets:
      ghcr_username: ${{ secrets.GHCR_USERNAME }}
      ghcr_token: ${{ secrets.GHCR_TOKEN }}
