---
name: Test, Build & Push Image for a Release to Master
on:
  release:
    branches:
      - master
    types: [ published ]
jobs:
  test:
    uses: ./.github/workflows/test.yml
  build_push:
    needs: test
    uses: ./.github/workflows/build-push-image.yml
    with:
      tag: ${{ github.event.release.tag_name }}
    secrets:
      ghcr_username: ${{ secrets.GHCR_USERNAME }}
      ghcr_token: ${{ secrets.GHCR_TOKEN }}
