---
name: Ensure Semantic Version
on:
  workflow_call:
    inputs:
      semver:
        required: true
        type: string
jobs:
  ensure-semver:
    runs-on: ubuntu-latest
    steps:
      - name: Validate "semver" as a semantic version
        id: check-tag
        run: |-
          if [[ '${{ inputs.semver}}' =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo ::set-output name=match::true
          fi
      - name: Report semver Check
        if: steps.check-tag.outputs.match != 'true'
        run: echo "Release version must follow semantic naming (e.g. 1.0.2)"; exit 1