---
name: Test (unit, integration)
on:
  workflow_call:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out GitHub Repo
        uses: actions/checkout@v2

      - uses: actions/setup-python@v3
        with:
          python-version: '3.7'

      - name: Install pipenv
        run: pip install -r requirements.txt

      - name: Install test dependencies and config
        run: make test-setup

      # Run tests
      - name: Run all tests
        run: make test

      # Display a coverage report for inspection in the workflow logs
      - name: Coverage summary
        run: make coverage-summary

      - name: Send to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./cov_profile.lcov
