---
name: Ensure Semantic Version
on:
  workflow_call:
    inputs:
      semver:
        required: true
        type: string
jobs:
  ensure-semver:
    runs-on: ubuntu-latest
    steps:
      - name: Validate "semver" as a semantic version
        uses: actions/github-script@v6
        with:
          script: |
            const semver = '${{ inputs.semver }}';
            if (!/^[0-9]+\.[0-9]+\.[0-9]+$/.test(semver)) {
              core.setFailed(`Release version must follow semantic version naming (e.g. 1.0.2) but is "${semver}"`)
            }
